version: '3.3'

services:
  db:
    image: pgvector/pgvector:pg14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5

    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A beat beat --loglevel=INFO
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker

  scraper:
    build: .
    environment:
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - ./images:/app/images
    working_dir: /app
    depends_on:
      - db
      - redis
      - celery_beat
      - celery_worker
    command: scrapy crawl giphy
volumes:
  pgdata: